let RAW=[],DATA=[],LOOKUPS={},MONTHS=[],BASE=[];let deferredPrompt=null;
const $=s=>document.querySelector(s);const $$=s=>Array.from(document.querySelectorAll(s));
const money=v=>fmtMoney.format(v||0), num=v=>fmtNum.format(v||0);
const uniq=arr=>[...new Set(arr.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es'));
const rowObj=r=>({division:LOOKUPS.division[r[0]],dm:LOOKUPS.dm[r[1]],anio:r[2],semana:r[3],mes:MONTHS[(r[4]||1)-1]||'',mesNum:r[4],tienda:LOOKUPS.tienda[r[5]],categoria:LOOKUPS.categoria[r[6]],ingrediente:LOOKUPS.ingrediente[r[7]],costoUnitario:r[8],varianza:r[9],costoVarianza:r[10],impacto:r[9]>0?'Faltante':r[9]<0?'Sobrante':'Sin variación'});
function group(arr,key,measure='costoVarianza'){const m=new Map();arr.forEach(r=>{const k=typeof key==='function'?key(r):r[key];m.set(k,(m.get(k)||0)+(r[measure]||0));});return [...m.entries()].map(([k,v])=>({k,v}));}
function groupAbs(arr,key){const m=new Map();arr.forEach(r=>{const k=typeof key==='function'?key(r):r[key];m.set(k,(m.get(k)||0)+Math.abs(r.costoVarianza||0));});return [...m.entries()].map(([k,v])=>({k,v}));}
function setOptions(sel,values,label='Todos'){const cur=sel.value;sel.innerHTML=`<option value="all">${label}</option>`+values.map(v=>`<option value="${String(v).replaceAll('"','&quot;')}">${v}</option>`).join('');if(values.includes(cur))sel.value=cur;}
function getFilters(){return {y:$('#yearFilter').value,m:$('#monthFilter').value,w:$('#weekFilter').value,dm:$('#dmFilter').value,st:$('#storeFilter').value,cat:$('#categoryFilter').value,ing:$('#ingredientFilter').value,imp:$('#impactFilter').value,q:$('#searchInput').value.trim().toLowerCase()}}
function pass(r,f){if(f.y!='all'&&r.anio!=f.y)return false;if(f.m!='all'&&r.mes!=f.m)return false;if(f.w!='all'&&r.semana!=f.w)return false;if(f.dm!='all'&&r.dm!=f.dm)return false;if(f.st!='all'&&r.tienda!=f.st)return false;if(f.cat!='all'&&r.categoria!=f.cat)return false;if(f.ing!='all'&&r.ingrediente!=f.ing)return false;if(f.imp==='sobrante'&&r.varianza>=0)return false;if(f.imp==='faltante'&&r.varianza<=0)return false;if(f.imp==='alto'&&Math.abs(r.costoVarianza)<APP_CONFIG.riskLimit)return false;if(f.q&&!`${r.dm} ${r.tienda} ${r.categoria} ${r.ingrediente}`.toLowerCase().includes(f.q))return false;return true}
function refreshFilterOptions(scope){const f=getFilters();let partial=DATA.filter(r=>(f.y=='all'||r.anio==f.y)&&(f.m=='all'||r.mes==f.m)&&(f.dm=='all'||r.dm==f.dm));setOptions($('#yearFilter'),uniq(DATA.map(r=>r.anio)),'Todos');setOptions($('#monthFilter'),APP_CONFIG.monthOrder.filter(m=>DATA.some(r=>r.mes===m)),'Todos');setOptions($('#weekFilter'),uniq(partial.map(r=>r.semana)).sort((a,b)=>a-b),'Todas');setOptions($('#dmFilter'),uniq(DATA.map(r=>r.dm)),'Todos');setOptions($('#storeFilter'),uniq(partial.filter(r=>f.dm=='all'||r.dm==f.dm).map(r=>r.tienda)),'Todas');setOptions($('#categoryFilter'),uniq(partial.map(r=>r.categoria)),'Todas');setOptions($('#ingredientFilter'),uniq(partial.filter(r=>f.cat=='all'||r.categoria==f.cat).map(r=>r.ingrediente)),'Todos');}
function filtered(){const f=getFilters();return DATA.filter(r=>pass(r,f));}
function calcKpis(arr){let total=arr.reduce((a,r)=>a+r.costoVarianza,0),abs=arr.reduce((a,r)=>a+Math.abs(r.costoVarianza),0);let sob=arr.filter(r=>r.varianza<0),fal=arr.filter(r=>r.varianza>0);let sobD=sob.reduce((a,r)=>a+r.costoVarianza,0),falD=fal.reduce((a,r)=>a+r.costoVarianza,0),sobU=sob.reduce((a,r)=>a+r.varianza,0),falU=fal.reduce((a,r)=>a+r.varianza,0);let score=Math.max(0,Math.round(100-(abs/Math.max(1,arr.length))/25));return {total,abs,sobD,falD,sobU,falU,score,productos:uniq(arr.map(r=>r.ingrediente)).length,tiendas:uniq(arr.map(r=>r.tienda)).length,regs:arr.length}}
function renderKpis(k){$('#healthScore').textContent=k.score+'%';$('#healthText').textContent=k.score>=80?'Control visual sano':'Revisar productos con recurrencia e impacto.';$('#kpis').innerHTML=[['Impacto neto',money(k.total),`${k.regs.toLocaleString('es-MX')} registros`],['Faltantes $',money(k.falD),`${num(k.falU)} unidades positivas`],['Sobrantes $',money(k.sobD),`${num(k.sobU)} unidades negativas`],['Productos',k.productos,`${k.tiendas} tiendas filtradas`],['Impacto absoluto',money(k.abs),'Faltantes + sobrantes']].map(x=>`<div class="kpi"><small>${x[0]}</small><b>${x[1]}</b><div class="sub">${x[2]}</div></div>`).join('')}
function renderCharts(arr){const mode=$('#trendMode').value;let trend;if(mode==='week'){trend=group(arr,r=>`S${String(r.semana).padStart(2,'0')}`).sort((a,b)=>+a.k.slice(1)-+b.k.slice(1));}else{trend=APP_CONFIG.monthOrder.map(m=>({k:m,v:arr.filter(r=>r.mes===m).reduce((a,r)=>a+r.costoVarianza,0)})).filter(x=>x.v!==0)}MiniChart.line($('#moneyTrend'),trend.map(x=>x.k),[{data:trend.map(x=>x.v),color:'#006241'}]);const falt=arr.filter(r=>r.varianza>0).reduce((a,r)=>a+Math.abs(r.costoVarianza),0), sobr=arr.filter(r=>r.varianza<0).reduce((a,r)=>a+Math.abs(r.costoVarianza),0);MiniChart.doughnut($('#impactSplit'),[{value:falt,color:'#111'},{value:sobr,color:'#cf2e2e'}]);let top=groupAbs(arr,'ingrediente').sort((a,b)=>b.v-a.v).slice(0,12);MiniChart.bars($('#topProducts'),top.map(x=>x.k),top.map(x=>arr.filter(r=>r.ingrediente===x.k).reduce((a,r)=>a+r.costoVarianza,0)));renderTreemap(arr);renderSelected(arr);renderHeatmap(arr);renderPareto(arr);renderAlerts(arr);}
function renderTreemap(arr){let cats=groupAbs(arr,'categoria').sort((a,b)=>b.v-a.v).slice(0,10),max=Math.max(1,...cats.map(x=>x.v));$('#categoryTreemap').innerHTML=cats.map(x=>`<div class="tile" style="min-height:${80+(x.v/max)*110}px"><b>${x.k}</b><span>${money(x.v)}</span></div>`).join('')||'<p class="muted">Sin datos.</p>'}
function selectedIngredient(arr){let f=getFilters();if(f.ing!='all')return f.ing;let top=groupAbs(arr,'ingrediente').sort((a,b)=>b.v-a.v)[0];return top?top.k:null}
function renderSelected(arr){const ing=selectedIngredient(arr);$('#selectedProductTitle').textContent=ing?`Costo unitario · ${ing}`:'Costo unitario';let s=arr.filter(r=>r.ingrediente===ing).sort((a,b)=>a.semana-b.semana);let byW=uniq(s.map(r=>r.semana)).sort((a,b)=>a-b).map(w=>{let a=s.filter(r=>r.semana===w);return {label:'S'+w,costo:a.reduce((x,r)=>x+r.costoUnitario,0)/Math.max(1,a.length),money:a.reduce((x,r)=>x+r.costoVarianza,0),units:a.reduce((x,r)=>x+r.varianza,0)}});MiniChart.line($('#unitCostTrend'),byW.map(x=>x.label),[{data:byW.map(x=>x.costo),color:'#006241'}]);MiniChart.combo($('#selectedVariance'),byW.map(x=>x.label),byW.map(x=>x.money),byW.map(x=>x.units));}
function renderHeatmap(arr){let weeks=uniq(arr.map(r=>r.semana)).sort((a,b)=>a-b);$('#heatmap').innerHTML=weeks.map(w=>{let a=arr.filter(r=>r.semana===w),net=a.reduce((x,r)=>x+r.costoVarianza,0),u=a.reduce((x,r)=>x+r.varianza,0);let cls=u<0?'sobrante':u>0?'faltante':'mixed';return `<div class="heat ${cls}"><strong>S${w}</strong><small>${a[0]?.mes||''}</small><div>${money(net)}</div><small>${num(u)} u.</small></div>`}).join('')}
function renderPareto(arr){let items=groupAbs(arr,'ingrediente').sort((a,b)=>b.v-a.v).slice(0,15),total=items.reduce((a,x)=>a+x.v,0)||1;let acc=0;$('#pareto').innerHTML=items.map(x=>{acc+=x.v;let p=x.v/total*100;return `<div class="row"><div><b>${x.k}</b><div class="bar"><i style="width:${p}%"></i></div><small>${p.toFixed(1)}% · acumulado ${(acc/total*100).toFixed(1)}%</small></div><strong>${money(x.v)}</strong></div>`}).join('')}
function renderAlerts(arr){let top=groupAbs(arr,'ingrediente').sort((a,b)=>b.v-a.v).slice(0,5);let neg=arr.filter(r=>r.varianza<0).length,pos=arr.filter(r=>r.varianza>0).length;let html='';if(top[0])html+=`<div class="alert danger"><div><b>Validar ${top[0].k}</b><br><small>Mayor impacto absoluto filtrado. Revisar conteo, merma, ajustes y captura.</small></div><strong>${money(top[0].v)}</strong></div>`;html+=`<div class="alert warn"><div><b>Lectura operativa</b><br><small>${neg.toLocaleString('es-MX')} sobrantes negativos y ${pos.toLocaleString('es-MX')} faltantes positivos.</small></div><strong>Priorizar</strong></div>`;html+=`<div class="alert"><div><b>Rutina sugerida</b><br><small>Trabajar Top 10 de productos, luego categoría con mayor concentración y semanas recurrentes.</small></div><strong>80/20</strong></div>`;$('#alerts').innerHTML=html;}
function renderTable(arr){let tbody=$('#dataTable tbody');let sample=arr.slice(0,450);tbody.innerHTML=sample.map(r=>`<tr class="${r.varianza<0?'sobrante':r.varianza>0?'faltante':''}"><td>${r.dm}</td><td>${r.semana}</td><td>${r.mes}</td><td>${r.tienda}</td><td>${r.categoria}</td><td>${r.ingrediente}</td><td class="num">${money(r.costoUnitario)}</td><td class="num">${num(r.varianza)}</td><td class="num ${r.costoVarianza<0?'money-red':'money-black'}">${money(r.costoVarianza)}</td><td>${r.impacto}</td></tr>`).join('');$('#tableCount').textContent=`${arr.length.toLocaleString('es-MX')} registros${arr.length>450?' · mostrando 450':''}`}
function render(){refreshFilterOptions();let arr=filtered();renderKpis(calcKpis(arr));renderCharts(arr);renderTable(arr)}
function exportCSV(){let arr=filtered();let headers=['DM','Año','Mes','Semana','Tienda','Categoría','Ingrediente','Costo Unitario','Varianza','Costo Varianza','Tipo'];let rows=arr.map(r=>[r.dm,r.anio,r.mes,r.semana,r.tienda,r.categoria,r.ingrediente,r.costoUnitario,r.varianza,r.costoVarianza,r.impacto]);let csv=[headers,...rows].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');let blob=new Blob([csv],{type:'text/csv;charset=utf-8'});let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='variaciones_filtradas.csv';a.click();URL.revokeObjectURL(a.href)}
async function init(){try{const j=window.VAR_DATA||await fetch('data/data.json').then(r=>r.json());LOOKUPS=j.lookups;MONTHS=j.monthOrder;BASE=j.baseMesSemana;RAW=j.rows;DATA=RAW.map(rowObj);$('#lastUpdate').textContent=`${j.summary.records.toLocaleString('es-MX')} registros · ${j.summary.notes}`;setOptions($('#yearFilter'),uniq(DATA.map(r=>r.anio)),'Todos');setOptions($('#monthFilter'),APP_CONFIG.monthOrder,'Todos');render();$('#boot').classList.add('hide')}catch(e){$('#boot').innerHTML='<b>No se pudo cargar data/data.json</b><span>'+e.message+'</span>'}}
['yearFilter','monthFilter','weekFilter','dmFilter','storeFilter','categoryFilter','ingredientFilter','impactFilter','trendMode'].forEach(id=>$('#'+id).addEventListener('change',render));$('#searchInput').addEventListener('input',()=>requestAnimationFrame(render));$('#resetBtn').addEventListener('click',()=>{$$('select').forEach(s=>s.value='all');$('#searchInput').value='';render()});$('#exportCsv').addEventListener('click',exportCSV);$('#printBtn').addEventListener('click',()=>print());$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('varTheme',document.body.classList.contains('dark')?'dark':'light');render()});if(localStorage.getItem('varTheme')==='dark')document.body.classList.add('dark');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').addEventListener('click',async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;$('#installBtn').classList.add('hidden')}});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');init();
