const S={raw:[],base:[],data:[],filters:{},meta:{storeMap:new Map()},deferredPrompt:null};
const $=id=>document.getElementById(id);
const clean=v=>(v??'').toString().trim();
const num=v=>{if(v==null||v==='')return 0;if(typeof v==='number')return isFinite(v)?v:0;let s=String(v).replace(/[$,\s]/g,'').replace(/[()]/g,'-');let n=parseFloat(s);return isFinite(n)?n:0};
const key=s=>clean(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ');
const months=CONFIG.months;
function monthFromBase(y,w){const r=S.base.find(x=>+x['Año']===+y&&+x['Semana']===+w);return r?clean(r['Mes']):''}
function storeType(store){return S.meta.storeMap.get(key(store))||'Sin tipo'}
async function loadWorkbook(file){let buf;if(file){buf=await file.arrayBuffer()}else{const res=await fetch(CONFIG.dataPath,{cache:'no-store'});if(!res.ok)throw Error('No se pudo leer data/Variacion_Semanal.xlsx');buf=await res.arrayBuffer()}const wb=XLSX.read(buf,{type:'array'});S.base=XLSX.utils.sheet_to_json(wb.Sheets['Base_Mes_Semana']||wb.Sheets[wb.SheetNames[0]],{defval:''});let sh=wb.Sheets['Variacion_Semanal']||wb.Sheets[wb.SheetNames[1]];let rows=XLSX.utils.sheet_to_json(sh,{range:2,defval:''});S.raw=rows.map(r=>{let year=+r['Año']||2026, week=+r['Semana']||0, variance=num(r['Varianza (#)']), money=num(r['Costo de Varianza ($)']);let month=clean(r['Mes'])||monthFromBase(year,week)||'';let type=storeType(r['Tiendas']);return{division:clean(r['División']),dm:clean(r['DM']),year,week,month,store:clean(r['Tiendas']),type,cat:clean(r['Categoría Inventario']),item:clean(r['Ingrediente']),unit:num(r['Costo Unitario Promedio ($)']),qty:variance,money,absMoney:Math.abs(money),status:variance<0?'sobrante':variance>0?'faltante':'ok'}}).filter(r=>r.year&&r.week&&r.store&&r.item);initFilters();apply();$('boot').classList.add('hide')}
function initStoreMeta(){S.meta.storeMap=new Map();/* Opcional: pegar aquí catálogo simple Tienda=>Tipo. El tablero funciona sin este archivo. */}
function setOptions(id,arr,all='Todos'){let el=$(id),cur=el.value;let vals=[all,...[...new Set(arr.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),'es',{numeric:true}))];el.innerHTML=vals.map(v=>`<option value="${v}">${v}</option>`).join('');if(vals.includes(cur))el.value=cur}
function initFilters(){setOptions('fYear',S.raw.map(r=>r.year),'Todos');setOptions('fMonth',S.base.map(r=>r.Mes),'Todos');setOptions('fWeek',S.raw.map(r=>r.week),'Todas');setOptions('fDM',S.raw.map(r=>r.dm),'Todos');setOptions('fStore',S.raw.map(r=>r.store),'Todas');setOptions('fType',S.raw.map(r=>r.type),'Todos');setOptions('fCat',S.raw.map(r=>r.cat),'Todas');['fYear','fMonth','fWeek','fDM','fStore','fType','fCat','fMetric'].forEach(id=>$(id).addEventListener('change',apply));$('fSearch').addEventListener('input',apply);$('btnCSV').addEventListener('click',exportCSV);$('btnTheme').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('theme')==='dark')document.body.classList.add('dark')}
function filtered(){let f={year:$('fYear').value,month:$('fMonth').value,week:$('fWeek').value,dm:$('fDM').value,store:$('fStore').value,type:$('fType').value,cat:$('fCat').value,q:key($('fSearch').value)};return S.raw.filter(r=>(f.year==='Todos'||r.year==f.year)&&(f.month==='Todos'||r.month===f.month)&&(f.week==='Todas'||r.week==f.week)&&(f.dm==='Todos'||r.dm===f.dm)&&(f.store==='Todas'||r.store===f.store)&&(f.type==='Todos'||r.type===f.type)&&(f.cat==='Todas'||r.cat===f.cat)&&(!f.q||key(r.item).includes(f.q)||key(r.store).includes(f.q)||key(r.cat).includes(f.q)))}
function group(rows,field){const m=new Map();for(const r of rows){let k=r[field]||'Sin dato',o=m.get(k)||{key:k,money:0,abs:0,qty:0,short:0,over:0,rows:0};o.money+=r.money;o.abs+=Math.abs(r.money);o.qty+=r.qty;if(r.qty>0)o.short+=r.qty;if(r.qty<0)o.over+=Math.abs(r.qty);o.rows++;m.set(k,o)}return [...m.values()]}
function byWeek(rows){const m=new Map();for(const r of rows){let k=`${r.year}-S${String(r.week).padStart(2,'0')}`,o=m.get(k)||{key:k,year:r.year,week:r.week,month:r.month,money:0,qty:0,short:0,over:0,abs:0};o.money+=r.money;o.qty+=r.qty;o.abs+=Math.abs(r.money);if(r.qty>0)o.short+=r.qty;if(r.qty<0)o.over+=Math.abs(r.qty);m.set(k,o)}return [...m.values()].sort((a,b)=>a.year-b.year||a.week-b.week)}
function apply(){let rows=filtered();S.data=rows;updateKPI(rows);updateCharts(rows);updateRankings(rows);updateHeat(rows);updateInsights(rows);updateTable(rows)}
function updateKPI(rows){let money=rows.reduce((a,r)=>a+r.money,0),abs=rows.reduce((a,r)=>a+Math.abs(r.money),0),short=rows.reduce((a,r)=>a+(r.qty>0?r.qty:0),0),over=rows.reduce((a,r)=>a+(r.qty<0?Math.abs(r.qty):0),0);let items=new Set(rows.map(r=>r.item)).size;let score=Math.max(0,Math.min(100,Math.round(100-(abs/(abs+25000))*100)));$('kMoney').textContent=DashCharts.fmtMoney(money);$('kMoney').className=money<0?'red':'black';$('kShort').textContent=DashCharts.fmtNum(short);$('kOver').textContent=DashCharts.fmtNum(over);$('kItems').textContent=items;$('kScore').textContent=score;$('scoreBar').style.width=score+'%';$('kMoneyNote').textContent=`${rows.length.toLocaleString('es-MX')} registros filtrados`}
function updateCharts(rows){let w=byWeek(rows);DashCharts.trend(w.map(x=>`${x.month} S${x.week}`),w.map(x=>x.money),w.map(x=>x.qty));DashCharts.mix(w.slice(-10).map(x=>`S${x.week}`),w.slice(-10).map(x=>x.short),w.slice(-10).map(x=>x.over));$('trendHint').textContent=w.length?`${w[0].month} S${w[0].week} → ${w[w.length-1].month} S${w[w.length-1].week}`:'Sin datos';let top=group(rows,'item').sort((a,b)=>b.abs-a.abs).slice(0,10),total=top.reduce((a,x)=>a+x.abs,0)||1,acc=0;DashCharts.pareto(top.map(x=>x.key),top.map(x=>x.abs),top.map(x=>Math.round((acc+=x.abs)/total*100)));let count80=0,run=0;for(const x of group(rows,'item').sort((a,b)=>b.abs-a.abs)){if(run/(rows.reduce((a,r)=>a+Math.abs(r.money),0)||1)<.8){run+=x.abs;count80++}}$('paretoHint').textContent=count80?`${count80} productos explican ~80%`:'Sin datos'}
function updateRankings(rows){let g=group(rows,'item');rank('topShort',g.filter(x=>x.short>0).sort((a,b)=>b.short-a.short).slice(0,7),'short');rank('topOver',g.filter(x=>x.over>0).sort((a,b)=>b.over-a.over).slice(0,7),'over')}
function rank(id,arr,type){let max=Math.max(...arr.map(x=>type==='short'?x.short:x.over),1);$(id).innerHTML=arr.length?arr.map(x=>`<div class="rankItem"><b>${x.key}</b><strong>${DashCharts.fmtNum(type==='short'?x.short:x.over)}</strong><small>${DashCharts.fmtMoney(x.money)}</small><div class="miniBar"><i class="${type==='over'?'redline':''}" style="width:${Math.round((type==='short'?x.short:x.over)/max*100)}%"></i></div></div>`).join(''):'<div class="insight">Sin datos en el filtro actual.</div>'}
function updateHeat(rows){let w=byWeek(rows),max=Math.max(...w.map(x=>x.abs),1);$('heatmap').innerHTML=w.map(x=>{let op=.08+.82*(x.abs/max),bg=x.money<0?`rgba(198,40,40,${op})`:`rgba(17,24,39,${op})`;return`<div class="cell" style="background:${bg};color:${op>.45?'white':'inherit'}"><b>${x.month} · S${x.week}</b><small>${DashCharts.fmtMoney(x.money)}<br>${DashCharts.fmtNum(x.qty)} uds</small></div>`}).join('')||'<div class="insight">Sin datos.</div>'}
function updateInsights(rows){let topItem=group(rows,'item').sort((a,b)=>b.abs-a.abs)[0],topStore=group(rows,'store').sort((a,b)=>b.abs-a.abs)[0],weeks=byWeek(rows),last=weeks.at(-1),prev=weeks.at(-2);let trend=last&&prev?last.abs-prev.abs:0;let arr=[];if(topItem)arr.push(`<div class="insight"><b>Prioridad producto</b>${topItem.key} concentra ${DashCharts.fmtMoney(topItem.abs)} de impacto absoluto.</div>`);if(topStore)arr.push(`<div class="insight"><b>Tienda a revisar</b>${topStore.key} suma ${DashCharts.fmtMoney(topStore.abs)} de impacto.</div>`);if(last)arr.push(`<div class="insight"><b>Última semana</b>S${last.week}: ${DashCharts.fmtMoney(last.money)} · ${DashCharts.fmtNum(last.qty)} unidades.</div>`);if(prev)arr.push(`<div class="insight"><b>Tendencia</b>${trend>0?'Aumentó el impacto, requiere acción.':'Mejoró o se contuvo el impacto.'}</div>`);$('insights').innerHTML=arr.join('')||'<div class="insight">Ajusta filtros para generar hallazgos.</div>'}
function updateTable(rows){let body=$('detail').querySelector('tbody');body.innerHTML=rows.sort((a,b)=>b.absMoney-a.absMoney).slice(0,CONFIG.maxTableRows).map(r=>`<tr><td>${r.month}</td><td>${r.week}</td><td>${r.dm}</td><td>${r.store}</td><td>${r.type}</td><td>${r.cat}</td><td>${r.item}</td><td class="${r.qty<0?'red':'black'}">${DashCharts.fmtNum(r.qty)}</td><td class="${r.money<0?'red':'black'}">${DashCharts.fmtMoney(r.money)}</td></tr>`).join('')}
function exportCSV(){let rows=S.data;let head=['Año','Mes','Semana','DM','Tienda','Tipo','Categoría','Ingrediente','Varianza','Impacto'];let csv=[head.join(',')].concat(rows.map(r=>[r.year,r.month,r.week,r.dm,r.store,r.type,r.cat,r.item,r.qty,r.money].map(v=>`"${String(v).replace(/"/g,'""')}"`).join(','))).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='variaciones_filtradas.csv';a.click()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.deferredPrompt=e;$('btnInstall').hidden=false});$('btnInstall').onclick=()=>S.deferredPrompt?.prompt();$('fileInput').addEventListener('change',e=>e.target.files[0]&&loadWorkbook(e.target.files[0]));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');initStoreMeta();loadWorkbook().catch(err=>{$('boot').innerHTML=`<img src="assets/logo.svg"><h1>No se pudo cargar el Excel</h1><p>${err.message}</p><p>Usa el botón <b>Cargar Excel</b> y selecciona Variacion_Semanal.xlsx.</p>`;console.error(err)});
