const fmtMoney=new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0});
const fmtNum=new Intl.NumberFormat('es-MX',{maximumFractionDigits:1});
function cssVar(name){return getComputedStyle(document.documentElement).getPropertyValue(name).trim()}
class MiniChart{
  static clear(canvas){const ctx=canvas.getContext('2d');const dpr=window.devicePixelRatio||1;const w=canvas.clientWidth||canvas.parentElement.clientWidth;const h=canvas.getAttribute('height')||220;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);return {ctx,w,h:+h}}
  static axes(ctx,w,h){ctx.strokeStyle='rgba(0,0,0,.08)';ctx.lineWidth=1;for(let i=0;i<4;i++){let y=25+i*(h-55)/3;ctx.beginPath();ctx.moveTo(40,y);ctx.lineTo(w-15,y);ctx.stroke();}}
  static line(canvas,labels,series,opt={}){const {ctx,w,h}=this.clear(canvas);this.axes(ctx,w,h);const vals=series.flatMap(s=>s.data);let min=Math.min(0,...vals),max=Math.max(0,...vals);if(max===min){max=1;min=-1}const sx=i=>40+i*((w-60)/Math.max(1,labels.length-1));const sy=v=>h-30-((v-min)/(max-min))*(h-60);ctx.font='11px Inter,Arial';ctx.fillStyle=cssVar('--muted');labels.forEach((l,i)=>{if(i%Math.ceil(labels.length/8)===0){ctx.fillText(l,sx(i)-12,h-10)}});series.forEach(s=>{ctx.beginPath();ctx.lineWidth=3;ctx.strokeStyle=s.color;ctx.fillStyle=s.color; s.data.forEach((v,i)=>{let x=sx(i),y=sy(v);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();s.data.forEach((v,i)=>{let x=sx(i),y=sy(v);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();});});}
  static bars(canvas,labels,data,opt={}){const {ctx,w,h}=this.clear(canvas);const max=Math.max(1,...data.map(Math.abs));const barH=Math.max(8,(h-35)/Math.max(1,labels.length)-8);ctx.font='12px Inter,Arial';data.forEach((v,i)=>{const y=15+i*(barH+8);const width=(Math.abs(v)/max)*(w-190);ctx.fillStyle='rgba(0,98,65,.09)';ctx.fillRect(165,y,w-185,barH);ctx.fillStyle=v<0?cssVar('--red'):cssVar('--black');ctx.fillRect(165,y,width,barH);ctx.fillStyle=cssVar('--ink');ctx.fillText(labels[i].slice(0,22),10,y+barH-2);ctx.textAlign='right';ctx.fillText(fmtMoney.format(v),w-12,y+barH-2);ctx.textAlign='left';});}
  static doughnut(canvas,items){const {ctx,w,h}=this.clear(canvas);const cx=w/2,cy=h/2,r=Math.min(w,h)/2-18;const total=items.reduce((a,b)=>a+Math.abs(b.value),0)||1;let start=-Math.PI/2;items.forEach((it,i)=>{const val=Math.abs(it.value)/total*Math.PI*2;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,start,start+val);ctx.closePath();ctx.fillStyle=it.color;ctx.fill();start+=val});ctx.beginPath();ctx.arc(cx,cy,r*.55,0,Math.PI*2);ctx.fillStyle=cssVar('--paper');ctx.fill();ctx.fillStyle=cssVar('--ink');ctx.font='800 18px Inter';ctx.textAlign='center';ctx.fillText('Impacto',cx,cy-4);ctx.font='12px Inter';ctx.fillText(fmtMoney.format(total),cx,cy+17);ctx.textAlign='left';}
  static combo(canvas,labels,money,units){const {ctx,w,h}=this.clear(canvas);this.axes(ctx,w,h);let maxM=Math.max(1,...money.map(Math.abs));let maxU=Math.max(1,...units.map(Math.abs));const sx=i=>40+i*((w-60)/Math.max(1,labels.length-1));const syM=v=>h-30-((v+maxM)/(2*maxM))*(h-60);const syU=v=>h-30-((v+maxU)/(2*maxU))*(h-60);ctx.strokeStyle='rgba(0,0,0,.16)';ctx.beginPath();ctx.moveTo(40,syM(0));ctx.lineTo(w-15,syM(0));ctx.stroke();[['#006241',money,syM],['#111',units,syU]].forEach(([color,arr,sy])=>{ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=3;ctx.beginPath();arr.forEach((v,i)=>{let x=sx(i),y=sy(v);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();arr.forEach((v,i)=>{let x=sx(i),y=sy(v);ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill();});});ctx.fillStyle=cssVar('--muted');ctx.font='11px Inter';labels.forEach((l,i)=>{if(i%Math.ceil(labels.length/8)===0)ctx.fillText(l,sx(i)-12,h-10)});}
}
window.MiniChart=MiniChart;
